name: Fabriko
description: Management of user permissions and Mapbox accounts for geographic information systems
author: devgioele

inputs:
  config:
    description: Path to the YAML config file
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'
