rotate-mapbox-tokens: true
group-by:
  - ConsVAT
gis-files:
  raster:
    - name: temperature
      path: 'some url'
    - name: altitude
      path: 'some url'
  vector:
    - name: dataset
      path: 'some url'
# Admin access tokens need the following scopes:
# scopes:list
# uploads:read
# uploads:list
# uploads:write
# styles:list
# tokens:read
# tokens:write
# datasets:list
# datasets:write
# tilesets:list
# tilesets:read
# tilesets:write
mapbox-accounts:
  - username: devgioele
    admin-access-token: ${{ secrets.MAPBOX_ADMIN_DEVGIOELE }}
    # Match all groups
    groups-regex: .*
    gis-files:
      raster:
        - temperature
        - altitude
      vector:
        - dataset
  - username: devgioele2
    admin-access-token: ${{ secrets.MAPBOX_ADMIN_DEVGIOELE2 }}
    # Match all groups
    groups-regex: .*
    gis-files:
      raster:
        - altitude
      vector:
        - dataset
  - username: devgioele3
    admin-access-token: ${{ secrets.MAPBOX_ADMIN_DEVGIOELE3 }}
    # Match all groups
    groups-regex: .*
    gis-files:
      raster:
        - temperature
      vector:
        - dataset
permissions:
  - id: apple.nicoter-kanzi
    description: Gives access to the Nicoter Kanzi apple
  - id: apple.scilate-envy
    description: Gives access to the Scilate Envy apple
roles:
  - id: role1
    description: User role 1
    users-regex: .*@role1\\.eu
    mapbox-account: devgioele
    permissions:
      - apple.nicoter-kanzi
      - apple.scilate-envy
  - id: role2
    description: User role 2
    users-regex: test2@gmail\\.com
    mapbox-account: devgioele2
    permissions:
      - apple.nicoter-kanzi
  - id: role3
    description: User role 3
    users-regex: test3@gmail\\.com
    mapbox-account: devgioele3
    permissions:
      - apple.nicoter-kanzi
      - apple.scilate-envy
